import {
    mkdtemp,
    readFile,
    realpath,
    rm,
    stat,
    writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { pathToFileURL } from "node:url";
import {
    COMPLETION_SHELLS,
    type CompletionShell,
    CrafleetError,
} from "@crafleet/core";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { runCli } from "../application.js";

const mock = vi.hoisted(() => ({
    confirm: vi.fn(),
    select: vi.fn(),
    detect: vi.fn(),
    resolve: vi.fn(),
    apply: vi.fn(),
}));
vi.mock("@clack/prompts", async (original) => ({
    ...(await original<typeof import("@clack/prompts")>()),
    confirm: mock.confirm,
    select: mock.select,
    isCancel: (value: unknown) => typeof value === "symbol",
}));
vi.mock("@crafleet/adapters", async (original) => ({
    ...(await original<typeof import("@crafleet/adapters")>()),
    detectCompletionShell: mock.detect,
    resolveCompletionTarget: mock.resolve,
    applyCompletionSetup: mock.apply,
    diagnoseProject: async () => [
        { id: "fixture", status: "pass", message: "Fixture project checked." },
    ],
}));

import { applyCompletionSetup } from "../../../adapters/src/filesystem/completion-setup.js";

const parent = await realpath(tmpdir());
const entry = pathToFileURL(path.resolve("packages/cli/dist/cli.mjs")).href;
const oldExit = process.exitCode;
const ttyIn = Object.getOwnPropertyDescriptor(process.stdin, "isTTY");
const ttyErr = Object.getOwnPropertyDescriptor(process.stderr, "isTTY");
let root: string;
let stdout: string;
let stderr: string;
beforeEach(async () => {
    root = await mkdtemp(path.join(parent, "crafleet-setup-cli-"));
    vi.stubEnv("CRAFLEET_HOME", root);
    vi.stubEnv("CI", "false");
    Object.defineProperty(process.stdin, "isTTY", {
        configurable: true,
        value: true,
    });
    Object.defineProperty(process.stderr, "isTTY", {
        configurable: true,
        value: true,
    });
    stdout = "";
    stderr = "";
    process.exitCode = 0;
    vi.spyOn(process.stdout, "write").mockImplementation((chunk) => {
        stdout += String(chunk);
        return true;
    });
    vi.spyOn(process.stderr, "write").mockImplementation((chunk) => {
        stderr += String(chunk);
        return true;
    });
    for (const fn of Object.values(mock)) fn.mockReset();
    mock.detect.mockResolvedValue({ shell: "bash", executable: "/bin/bash" });
    mock.confirm.mockResolvedValue(true);
    mock.select.mockResolvedValue("fish");
    mock.apply.mockImplementation(applyCompletionSetup);
    mock.resolve.mockImplementation(async (shell: CompletionShell) => ({
        shell,
        scriptPath: path.join(root, `completion.${shell}`),
        profiles: shell === "fish" ? [] : [path.join(root, `profile.${shell}`)],
    }));
});
afterEach(async () => {
    vi.restoreAllMocks();
    vi.unstubAllEnvs();
    process.exitCode = oldExit;
    if (ttyIn) Object.defineProperty(process.stdin, "isTTY", ttyIn);
    else Reflect.deleteProperty(process.stdin, "isTTY");
    if (ttyErr) Object.defineProperty(process.stderr, "isTTY", ttyErr);
    else Reflect.deleteProperty(process.stderr, "isTTY");
    if (
        path.dirname(root) !== parent ||
        !path.basename(root).startsWith("crafleet-setup-cli-")
    )
        throw new Error("Unsafe cleanup");
    await rm(root, { recursive: true, force: true });
});
async function run(args: string[]) {
    stdout = "";
    stderr = "";
    process.exitCode = 0;
    await runCli(["-C", root, ...args], entry);
}
const reply = () => JSON.parse(stdout);

describe("completion setup CLI", () => {
    it.each(COMPLETION_SHELLS)(
        "retains script generation and adds confirmed installation for %s",
        async (shell) => {
            await run(["completion", shell]);
            expect(stdout).toContain(
                `Generated by crafleet completion ${shell}`,
            );
            expect(mock.detect).not.toHaveBeenCalled();
            await run(["completion", "install", shell]);
            expect(process.exitCode).toBe(0);
            expect(mock.confirm).toHaveBeenCalledTimes(1);
            expect(stderr).toContain(`Completion setup preview (${shell})`);
            expect(stdout).toContain("Open a new shell");
            expect(
                await readFile(path.join(root, `completion.${shell}`), "utf8"),
            ).toContain("sha256:");
            await run(["completion", "install", shell]);
            expect(mock.confirm).toHaveBeenCalledTimes(1);
        },
    );
    it.each(COMPLETION_SHELLS)(
        "previews %s without writes or prompts and installs with JSON --yes",
        async (shell) => {
            await run(["--json", "completion", "install", shell, "--dry-run"]);
            expect(reply().result.diagnostic.status).toBe("warn");
            expect(reply().ok).toBe(true);
            expect(mock.confirm).not.toHaveBeenCalled();
            await expect(
                stat(path.join(root, `completion.${shell}`)),
            ).rejects.toMatchObject({ code: "ENOENT" });
            await run(["completion", "install", shell, "--json"]);
            expect(reply().error.code).toBe("CONFIRMATION_REQUIRED");
            await run(["completion", "install", shell, "--yes", "--json"]);
            expect(reply().result.diagnostic.status).toBe("pass");
            expect(stdout.trim().split("\n")).toHaveLength(1);
        },
    );
    it.each([false, Symbol("cancel")])(
        "does not install when confirmation returns %s",
        async (answer) => {
            mock.confirm.mockResolvedValue(answer);
            await run(["completion", "install"]);
            expect(process.exitCode).toBe(130);
            expect(mock.apply).not.toHaveBeenCalled();
        },
    );
    it("selects an unknown shell interactively, requires input in JSON and reports doctor unknown", async () => {
        mock.detect.mockResolvedValue(undefined);
        await run(["completion", "install", "--json"]);
        expect(reply().error.code).toBe("INPUT_REQUIRED");
        await run(["doctor", "--json"]);
        expect(reply().result.at(-1)[0].id).toBe("completion.shell");
        await run(["completion", "install"]);
        expect(mock.select).toHaveBeenCalledTimes(1);
        expect(await stat(path.join(root, "completion.fish"))).toBeDefined();
    });
    it("handles cancelled shell selection", async () => {
        mock.detect.mockResolvedValue(undefined);
        mock.select.mockResolvedValue(Symbol("cancel"));
        await run(["doctor"]);
        expect(process.exitCode).toBe(130);
        expect(mock.apply).not.toHaveBeenCalled();
    });
    it.each([
        { flags: [] },
        { flags: ["--json"] },
        { flags: ["--dry-run"] },
        { flags: ["--yes"] },
    ])("doctor honors noninteractive flags $flags", async ({ flags }) => {
        if (!flags.length) vi.stubEnv("CI", "true");
        await run(["doctor", "--shell", "zsh", ...flags]);
        expect(mock.confirm).not.toHaveBeenCalled();
        expect(mock.apply).not.toHaveBeenCalled();
        expect(stdout).toContain("crafleet completion install zsh");
    });
    it("requires explicit approval in a non-TTY install", async () => {
        Object.defineProperty(process.stdin, "isTTY", {
            configurable: true,
            value: false,
        });
        await run(["completion", "install", "bash"]);
        expect(process.exitCode).toBe(3);
        expect(mock.confirm).not.toHaveBeenCalled();
    });
    it("doctor installs only after displaying the plan, rechecks and appends one host group", async () => {
        mock.confirm.mockImplementation(async () => {
            expect(stderr).toContain("# >>> crafleet completion >>>");
            expect(mock.apply).not.toHaveBeenCalled();
            return true;
        });
        await run(["doctor", "--shell", "powershell"]);
        expect(process.exitCode).toBe(0);
        expect(stdout).toContain("configured for future shell sessions");
        expect(stdout).toContain("load it in this terminal");
        await run(["doctor", "--shell", "powershell", "--json"]);
        expect(reply().result).toHaveLength(2);
        expect(reply().result.at(-1)[0].status).toBe("pass");
    });
    it("continues normal diagnosis after declining and cancels on Ctrl-C", async () => {
        mock.confirm.mockResolvedValue(false);
        await run(["doctor"]);
        expect(process.exitCode).toBe(0);
        expect(stdout).toContain("Fixture project checked");
        expect(mock.apply).not.toHaveBeenCalled();
        mock.confirm.mockResolvedValue(Symbol("cancel"));
        await run(["doctor"]);
        expect(process.exitCode).toBe(130);
    });
    it("does not offer to replace manual settings and never leaks profile contents", async () => {
        await writeFile(
            path.join(root, "profile.bash"),
            "SECRET='hidden'\nsource <(crafleet completion bash)\n",
        );
        await run(["doctor"]);
        expect(stdout).toContain("Manual completion settings");
        expect(mock.confirm).not.toHaveBeenCalled();
        await run(["completion", "install", "bash", "--dry-run", "--json"]);
        expect(reply().result.canApply).toBe(false);
        expect(stdout).not.toContain("hidden");
        await run(["completion", "install", "bash", "--yes", "--json"]);
        expect(reply().error.code).toBe("COMPLETION_CONFIG");
    });
    it("reports inspection and application failures without losing doctor results", async () => {
        mock.resolve.mockRejectedValueOnce(
            new CrafleetError(
                "COMPLETION_SHELL",
                "Unavailable",
                2,
                "Install the shell",
            ),
        );
        await run(["doctor", "--json"]);
        expect(reply().result.at(-1)[0].status).toBe("unknown");
        mock.apply.mockRejectedValue(
            new CrafleetError("COMPLETION_CHANGED", "Changed after preview", 3),
        );
        await run(["doctor"]);
        expect(process.exitCode).toBe(3);
        expect(stdout).toContain("Changed after preview");
        expect(stdout).toContain("Fixture project checked");
    });
    it("reports a failed post-install verification", async () => {
        mock.apply.mockResolvedValue(undefined);
        await run(["completion", "install", "--yes", "--json"]);
        expect(reply().error.code).toBe("COMPLETION_VERIFY");
    });
    it("includes operation policy and shell choices in structured help", async () => {
        await run(["completion", "install", "--help", "--json"]);
        expect(reply().result.policy).toMatchObject({
            effect: "change",
            target: "none",
        });
        expect(reply().result.arguments[0].choices).toEqual([
            ...COMPLETION_SHELLS,
        ]);
        await run(["doctor", "--help", "--json"]);
        expect(reply().result.policy).toMatchObject({
            effect: "read",
            interactiveSetup: "completion install",
        });
    });
});
