export const COMPLETION_SHELLS = ["bash", "zsh", "fish", "powershell"] as const;
export type CompletionShell = (typeof COMPLETION_SHELLS)[number];

export const COMPLETION_SCRIPTS: Record<CompletionShell, string> = {
    bash: `# Generated by crafleet completion bash. Source this file.
_crafleet_complete() {
    local candidate
    COMPREPLY=()
    while IFS= read -r candidate; do
        [[ -n $candidate ]] && COMPREPLY+=("$candidate")
    done < <(crafleet __complete --shell bash -- "\${COMP_WORDS[@]:1:COMP_CWORD}" 2>/dev/null)
    compopt -o filenames 2>/dev/null || true
}
complete -o filenames -F _crafleet_complete crafleet
`,
    zsh: `# Generated by crafleet completion zsh. Source after compinit.
_crafleet_complete() {
    local -a candidates
    candidates=("\${(@f)$(crafleet __complete -- "\${(@Q)words[2,CURRENT]}" 2>/dev/null)}")
    compadd -a candidates
}
compdef _crafleet_complete crafleet
`,
    fish: `# Generated by crafleet completion fish.
function __crafleet_complete
    set -l previous (commandline -opc)
    set -l current (commandline -ct)
    crafleet __complete -- $previous[2..-1] "$current" 2>/dev/null
end
complete -c crafleet -f -a '(__crafleet_complete)'
`,
    powershell: `# Generated by crafleet completion powershell. Dot-source this file.
Register-ArgumentCompleter -Native -CommandName crafleet -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)
    $crafleetWords = [System.Collections.Generic.List[string]]::new()
    foreach ($element in $commandAst.CommandElements | Select-Object -Skip 1) {
        if ($element.Extent.StartOffset -ge $cursorPosition) { break }
        if ($element -is [System.Management.Automation.Language.StringConstantExpressionAst]) {
            $crafleetWords.Add($element.Value)
        } elseif ($element -is [System.Management.Automation.Language.CommandParameterAst] -and !$element.Argument) {
            $crafleetWords.Add($element.Extent.Text)
        } else { return }
    }
    if (!$crafleetWords.Count -or $commandAst.CommandElements[-1].Extent.EndOffset -lt $cursorPosition) { $crafleetWords.Add('') }
    $crafleetArguments = @('__complete', '--') + $crafleetWords.ToArray()
    crafleet @crafleetArguments 2>$null | ForEach-Object {
        if (!$_) { return }
        $candidate = [string]$_
        $quoted = if ($candidate -match '^[a-zA-Z0-9_./:=@-]+$') { $candidate } else { "'" + $candidate.Replace("'", "''") + "'" }
        [System.Management.Automation.CompletionResult]::new($quoted, $candidate, 'ParameterValue', $candidate)
    }
}
`,
};
